# Generated by Django 5.1.2 on 2024-11-03 13:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='item_model',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('img_link', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=1000)),
                ('specification', models.CharField(max_length=400)),
                ('item_cost', models.IntegerField()),
                ('item_type', models.CharField(choices=[('solar_panel', 'solar_panel'), ('battery', 'battery')], max_length=20)),
                ('item_voltage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('item_capacity', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('item_power', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='item2plant_model',
            fields=[
                ('relate_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('plant_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('test_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'item2plant',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('item_id', 'plant_id'), name='unique item in plant')],
            },
        ),
        migrations.CreateModel(
            name='plant_model',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_status', models.CharField(choices=[('draft', 'draft'), ('deleted', 'deleted'), ('completed', 'completed'), ('formed', 'formed'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2024, 11, 3, 13, 32, 28, 959512))),
                ('forming_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('finishing_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('creator_login', models.CharField(max_length=50)),
                ('moderator_login', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('generation', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('saving', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=8, null=True)),
                ('fio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель акции')),
            ],
            options={
                'db_table': 'plants',
                'managed': True,
            },
        ),
    ]
