# Generated by Django 5.1.3 on 2024-11-08 17:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_model',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('img_link', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=1000)),
                ('specification', models.CharField(max_length=400)),
                ('item_cost', models.IntegerField()),
                ('item_type', models.CharField(choices=[('solar_panel', 'solar_panel'), ('battery', 'battery')], max_length=20)),
                ('item_voltage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('item_capacity', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('item_power', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='plant_model',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_status', models.CharField(choices=[('draft', 'draft'), ('deleted', 'deleted'), ('completed', 'completed'), ('formed', 'formed'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2024, 11, 8, 17, 27, 37, 406732))),
                ('forming_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('finishing_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('creator_login', models.CharField(max_length=50, null=True)),
                ('moderator_login', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('generation', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('saving', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=8, null=True)),
                ('fio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('creator', models.ForeignKey(db_column='creator', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, db_column='moderator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='queue_moderator_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='item2plant_model',
            fields=[
                ('relate_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolarPlants.item_model')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolarPlants.plant_model')),
            ],
            options={
                'db_table': 'item2plant',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('item_id', 'plant_id'), name='unique item in plant')],
            },
        ),
    ]
