# Generated by Django 5.1.3 on 2024-11-08 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 17, 27, 58, 594495)),
        ),
    ]
