# Generated by Django 5.1.2 on 2024-11-03 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0002_alter_plant_model_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 13, 41, 14, 288381)),
        ),
    ]
