# Generated by Django 5.1.3 on 2024-11-08 19:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0002_alter_plant_model_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_model',
            name='creator_login',
        ),
        migrations.RemoveField(
            model_name='plant_model',
            name='moderator_login',
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 19, 48, 34, 635999)),
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='moderator',
            field=models.ForeignKey(blank=True, db_column='moderator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plant_moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
