# Generated by Django 5.1.2 on 2024-11-04 15:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0004_remove_item2plant_model_test_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item2plant_model',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item2plant_model',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolarPlants.item_model'),
        ),
        migrations.AlterField(
            model_name='item2plant_model',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolarPlants.plant_model'),
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 15, 9, 35, 407715)),
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='creator_login',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель станции'),
        ),
    ]
