# Generated by Django 5.1.2 on 2024-11-04 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0005_alter_item2plant_model_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item2plant_model',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item2plant_model',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 15, 28, 17, 131760)),
        ),
    ]
