# Generated by Django 5.1.2 on 2024-10-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item2plant_model',
            fields=[
                ('relate_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('plant_id', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'item2plant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='item_model',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_status', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('img_link', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=1000)),
                ('specification', models.CharField(max_length=400)),
                ('item_cost', models.IntegerField()),
                ('item_type', models.CharField(max_length=10)),
                ('item_voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_power', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='plant_model',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_status', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField()),
                ('forming_date', models.DateTimeField()),
                ('finishing_date', models.DateTimeField()),
                ('creator_login', models.CharField(max_length=50)),
                ('moderator_login', models.CharField(max_length=50)),
                ('generation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saving', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('fio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'plants',
                'managed': False,
            },
        ),
    ]
